version: '3'

services:
  dev:
    build:
      context: .
      dockerfile: ./Dockerfile.development
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    command: npm run start:dev
    volumes:
      - .:/usr/src/caseservice
      - /usr/src/caseservice/node_modules
    # restart: unless-stopped
    environment:
      NODE_ENV: development
    #   - DB_URL=mongodb://caseservice_db
    networks:
      - caseservice-follow-up-network
  
  mongodb:
    image : mongo:latest
    container_name: caseservice_db
    volumes:
      - mongodata:/data/caseservice-follow-up-db
    ports:
      - 27017:27017
    networks:
      - caseservice-follow-up-network
    restart: always

volumes:
  mongodata: 
  

networks:
  caseservice-follow-up-network:
    driver: bridge