# syntax=docker/dockerfile:1
FROM node:16 AS build

WORKDIR /usr/src/caseservice

COPY package*.json ./

RUN npm install

COPY . .

RUN npm run build 

FROM node:16 AS production

ARG NODE_ENV=production
ENV NODE_ENV=${NODE_ENV}

WORKDIR /usr/src/caseservice

COPY package*.json ./

RUN npm install --only=production

COPY . .

COPY --from=build /usr/src/caseservice/dist ./dist

CMD ["node", "dist/main"]